name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  Linux:
    name: Linux

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        cxx: [g++, clang++]
      fail-fast: false
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: tdulcet/Table-and-Graph-Libs
        path: Table-and-Graph-Libs
    - name: Before script
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cppcheck
        cp -v Table-and-Graph-Libs/{tables,graphs}.hpp .
        $CXX --version
    - name: Script
      run: |
        ARGS=( -std=gnu++17 -Wall -g -Og )
        if [[ $CXX =~ ^clang ]]; then
            ARGS+=( -fsanitize=address,undefined,integer )
        else
            ARGS+=( -fsanitize=address,undefined )
        fi
        $CXX "${ARGS[@]}" table.cpp -o table
        ./table --help
        $CXX "${ARGS[@]}" graph.cpp -o graph
        ./graph --help
    - name: Cppcheck
      run: cppcheck --enable=all .
    - name: Clang-Tidy
      if: ${{ matrix.cxx == 'clang++' }}
      run: clang-tidy -checks='bugprone-*,-bugprone-easily-swappable-parameters,cert-*,clang-analyzer-*,misc-*,-misc-no-recursion,modernize-*,-modernize-use-trailing-return-type,performance-*,portability-*,readability-const-return-type,readability-container-*,readability-duplicate-include,readability-else-after-return,readability-make-member-function-cons,readability-non-const-parameter,readability-redundant-*,readability-simplify-*,readability-string-compare,readability-use-*' -header-filter='.*' *.cpp -- -Wall -O3 -std=c++17
